### PR TITLE
Added python version of Sally + Fixed some of your markdown violations

### PR DESCRIPTION
**Pull request by whois-hoeless**
I know.. even markdown has rules, don't ask.
Anyways this is my python version, you can try it out yourself before you commit it to your repo I think it works pretty well and I am pretty happy that it is ready now. It can also do OCR already, everything should work fine, try it out and let me know if you like it :)

### CODE REVIEW

**Comment by rwf93** [comment]
Outsiders perspective: I'd highly recommend splitting the ai functionality into a cog and also using .env files (making sure to gitignore them). I also recommend you to use [python venvs](https://docs.python.org/3/library/venv.html) and [freeze](https://pip.pypa.io/en/stable/cli/pip_freeze/) your dependencies to a requirements.txt. (you can use [CarlBot](https://github.com/rwf93/carlbot) as an example)

This is also highly applicable for the C# implementation in the context of .env. Keeping secrets in a .cs file that is tracked by git is a recipie for disaster :).

**Comment by whois-hoeless** [comment]
I'll do that, I got another repo open for it anyways, so far I actually had no problems running it without a venv since the packages that I use don't get major updates that could break them. I'll look into it tho, id love to make it even better

**Comment by whois-hoeless** [comment]
So I implemented your Idea with the .env file [here](https://github.com/whois-hoeless/Sally.py), it works quiet nicely, thanks for the advice. I also mentioned you and your bot in my repo :) 
I did not implement the cog thing (yet, I might do that too soon, depends on how bored I'll get) because I would need to rewrite my entire code to use classes and I don't really see the reason for my bot to use cogs, since I only listen to messages and then execute functions based on them, aka I don't have many commands nor listeners. Something that I am unfamiliar with is also if I need to make my other functions async or if they just work as they are. I did not test wether the history list I use gets messed up when lots of people use it at once ( and I don't know if using async fixes that ), so if you have any more info on that for me then that would be awesome :) ( I don't have too much experience with discord bots and async functions )

**Comment by DeSinc** [comment]
yeah I would just make a new repo, I thought about it and there's no way I'd put all this python code in here especially since I just updated everything on the c# side I would never want to have some outdated confusing .py code sitting around in files un-updated confusing people

**Comment by whois-hoeless** [comment]
I did and I am also updating things ofc

**Pull request closed without merging**
